export default{
    // 'basicExtend1': () => require.ensure([], require => require('./basic/extend1.vue'), 'basic'),
    'basicLayoutLayout1': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/layout/layout1'),
    'basicLayoutLayout2': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/layout/layout2'),
    'basicGridGrid1': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/grid/grid1'),
    'basicGridGrid2': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/grid/grid2'),
    'basicButtonType': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/type'),
    'basicButtonGhost': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/ghost'),
    'basicButtonButton1': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/button1'),
    'basicButtonButton2': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/button2'),
    'basicButtonButton3': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/button3'),
    'basicButtonButton4': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/button4'),
    'basicButtonSize': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/size'),
    'basicButtonBlock': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/block'),
    'basicButtonDisabled': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/disabled'),
    'basicButtonIcon': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/icon'),
    'basicButtonButton9': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/button9'),
    'basicButtonGroup': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/button/group'),
    'basicLinkLink1': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/link/link1'),
    'basicLinkLink2': () => import(/* webpackChunkName: "yo-component-basic" */ './basic/link/link2'),
    
    'formFormForm1': () => import(/* webpackChunkName: "yo-component-form" */ './form/form/form1'),
    'formFormForm2': () => import(/* webpackChunkName: "yo-component-form" */ './form/form/form2'),
    
    'formInputInput1': () => import(/* webpackChunkName: "yo-component-form" */ './form/input/input1'),
    'formInputInput2': () => import(/* webpackChunkName: "yo-component-form" */ './form/input/input2'),
    'formRadioRadio1': () => import(/* webpackChunkName: "yo-component-form" */ './form/radio/radio1'),
    'formRadioRadio2': () => import(/* webpackChunkName: "yo-component-form" */ './form/radio/radio2'),
    'formCheckboxCheckbox1': () => import(/* webpackChunkName: "yo-component-form" */ './form/checkbox/checkbox1'),
    'formCheckboxCheckbox2': () => import(/* webpackChunkName: "yo-component-form" */ './form/checkbox/checkbox2'),
    
    'navigationBreadcrumbBreadcrumb1': () => import(/* webpackChunkName: "yo-component-navigation" */ './navigation/breadcrumb/breadcrumb1'),
    'navigationBreadcrumbBreadcrumb2': () => import(/* webpackChunkName: "yo-component-navigation" */ './navigation/breadcrumb/breadcrumb2'),
}